import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Timeline from '../components/Timeline'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SNS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Timeline />
      </div>
    </>
  )
}

export default Home
